#!/bin/bash

#Submit this script with: sbatch calibrate_script

#SBATCH --time=2:00:00   # walltime
#SBATCH --ntasks=1         # number of processor cores (i.e. tasks)
#SBATCH --nodes=1          # number of nodes
#SBATCH --gres gpu:1
#SBATCH --mem-per-cpu=64G
#SBATCH -J "FNO-Catheter"    # job name
#SBATCH --output=FNO-Catheter.out  


python -u train.py   > fno-train.out 


